### ISSUE TITLE
Oxford Nanopore Version?

### ISSUE THREAD

**Issue by sogriffin98** [raymondkiu/fastq_info#4]
Hi Raymond,

Thanks so much for providing this tool. It worked great.

I was wondering if the same could be done for long reads, more specifically Oxford Nanopore?

Thanks :)

**Comment by raymondkiu** [comment]
Sorry for the delay in responding as I am not monitoring the GitHub for quite a while. Glad to know that it worked for you. Unfortunately I don't think it will work perfectly for ONT reads although they have the same fastq format but it has different number of nucleotides each read. I am not aware of any tools that can do that maybe check with ONT?
